# Generated by Django 5.2 on 2025-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
                ('phoneNumber', models.IntegerField(max_length=9, unique=True, verbose_name='Numéro téléphonique')),
                ('categorie', models.CharField()),
                ('city', models.CharField(verbose_name='Ville de résidence')),
            ],
        ),
    ]
