# Generated by Django 5.2 on 2025-05-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.IntegerField(unique=True, verbose_name='Numéro téléphonique'),
        ),
    ]
